let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'bash install.sh',}
Plug 'junegunn/fzf'
call plug#end()

if exists('$TMUX')
	autocmd BufEnter * call system("tmux rename-window " . "'" . "VIM:" . expand("%:t") . "'")
	autocmd VimLeave * call system("tmux set-window-option automatic-rename on")
endif

let $nproc = system('echo -n $(( $(nproc) / 2))')

let g:LanguageClient_serverCommands = {
	\ 'cpp': ['clangd', '-j', $nproc, '-completion-style=detailed', '-background-index', '-all-scopes-completion', '--suggest-missing-includes'],
	\ 'c': ['clangd', '-j', $nproc, '-completion-style=detailed', '-background-index', '-all-scopes-completion', '--suggest-missing-includes'],
	\ 'python': ['pyls'],
	\ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
	\ }

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'
"let g:airline_statusline_ontop = 3
set nu
set ic

set foldmethod=syntax
set foldnestmax=1
set foldlevel=1
set hidden
" cscope
if filereadable("cscope.out")
	try
		cs add cscope.out
	catch
		"cscope might be loaded already"
	endtry
endif
" find references
nmap R :cs f c <cword><CR>
" find symbols
nmap S :cs f s <cword><CR>
" find definitions
nmap D :cs f g <cword><CR>
" find assignments
nmap A :cs f a <cword><CR>
" or LanguageClient!
nmap M <Plug>(lcn-menu)
nmap D <Plug>(lcn-definition)
nmap R <Plug>(lcn-references)
nmap A <Plug>(lcn-code-action)

map <C-PageUp> :bp<CR>
map <C-PageDown> :bn<CR>

set hlsearch
" show tab
set list
set listchars=tab:⋮\ >

" wildchar completion
set wildmenu
set wildmode=list:longest:full,full
